const SET_THREADS = 'SET_CHAT_THREADS';
const SET_OLD_THREADS = 'SET_OLD_THREADS';
const SET_MESSAGES = 'SET_CHAT_MESSAGES';
const SET_MESSAGE = 'SET_CHAT_MESSAGE';
const SET_OLD_MESSAGE = 'SET_OLD_MESSAGE';
const SET_LOADING = 'SET_CHAT_LOADING';
const SET_ERROR = 'SET_CHAT_ERROR';

export {
  SET_THREADS,
  SET_OLD_MESSAGE,
  SET_OLD_THREADS,
  SET_MESSAGE,
  SET_MESSAGES,
  SET_LOADING,
  SET_ERROR,
};
