export const SET_SERVICES = 'SET_SERVICE_SERVICES';
export const SET_CATEGORIES = 'SET_SERVICE_CATEGORIES';
export const SET_ERROR = 'SET_SERVICE_ERROR';
export const SET_LOADING = 'SET_SERVICE_LOADING';
export const SET_FILTER = 'SET_SERVICE_FILTER';
