const SIGN_IN = 'SIGN_IN';
const LOGOUT = 'LOGOUT';
const SET_LOADING = 'SET_AUTH_LOADING';
const SET_ERROR = 'SET_AUTH_ERROR';
const REFRESH_TOKEN = 'REFRESH_AUTH_TOKEN';

export { SIGN_IN, LOGOUT, SET_LOADING, SET_ERROR, REFRESH_TOKEN };
