export const SET_PROFILE = 'SET_USER_PROFILE';
export const SET_LOADING = 'SET_USER_LOADING';
export const SET_PROFILE_ADS = 'SET_USER_ADS';
export const SET_NOTIFICATION_SETTINGS = 'SET_NOTIFICATION_SETTINGS';
export const SET_PROFILE_ADS_STATUS = 'SET_USER_ADS_STATUS';
