export const SET_EVENTS_LIST = 'SET_EVENTS_LIST';
export const SET_EVENTS_DETAIL = 'SET_EVENTS_DETAIL';
export const SET_FILTER = 'SET_EVENTS_FILTER';
export const SET_CATEGORIES = 'SET_EVENTS_CATEGORIES';
export const SET_ERROR = 'SET_EVENTS_ERROR';
export const SET_LOADING = 'SET_EVENTS_LOADING';
