const SET_LIST = 'SET_ADS_LIST';
const SET_DETAIL = 'SET_ADS_DETAIL';
const SET_CATEGORIES = 'SET_ADS_CATEGORIES';
const SET_FILTER = 'SET_ADS_FILTER';
const SET_LOADING = 'SET_ADS_LOADING';
const SET_ERROR = 'SET_ADS_ERROR';
const SET_LOAD_MORE = 'SET_ADS_LOAD_MORE';
const SET_FAVORITES_LIST = 'SET_ADS_FAVORITES_LIST';
const SET_SELLER_PROFILE = 'SET_SELLER_PROFILE';
const SET_ADS_TO_FAVORITE = 'SET_ADS_TO_FAVORITES_LIST';

export {
  SET_LIST,
  SET_DETAIL,
  SET_CATEGORIES,
  SET_FILTER,
  SET_LOAD_MORE,
  SET_LOADING,
  SET_ERROR,
  SET_FAVORITES_LIST,
  SET_SELLER_PROFILE,
  SET_ADS_TO_FAVORITE,
};
